stages: [build, test, analysis]

variables:
  LC_ALL: "C"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y clang python3 python3-pip cppcheck
  - python3 -m pip install --upgrade pip
  - pip install pytest pyyaml

build:
  stage: build
  script:
    - mkdir -p build artifacts
    - clang -Wall -Wextra -O2 src/thermal_control.c -o build/tcs
  artifacts:
    paths:
      - build/tcs
    expire_in: 1 week

test:
  stage: test
  needs: [build]
  script:
    - mkdir -p artifacts
    - python3 tools/gen_matrix.py || true
    - pytest -q --junitxml=artifacts/junit.xml
  artifacts:
    when: always
    reports:
      junit: artifacts/junit.xml
    paths:
      - artifacts/
    expire_in: 1 week

cppcheck:
  stage: analysis
  script:
    - cppcheck --enable=warning,style,performance,portability \
               --error-exitcode=1 \
               --inline-suppr \
               src/thermal_control.c

