name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    - cron: "0 5 * * *" # daily @ 05:00 UTC (~08:00 Athens)

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  LC_ALL: C
  PYTHON_VERSION: "3.11"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          mkdir -p build artifacts
          clang -Wall -Wextra -O2 src/thermal_control.c -o build/tcs

      - name: Generate Test Matrix (optional)
        run: |
          if [ -f tools/gen_matrix.py ]; then python3 tools/gen_matrix.py || true; fi

      - name: Run tests (pytest)
        run: |
          pytest -q --junitxml=artifacts/junit.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: artifacts/

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: |
          cppcheck --enable=warning,style,performance,portability \
                   --error-exitcode=1 \
                   --inline-suppr \
                   src/thermal_control.c

